spring.application.name=backend

server.port=3000

spring.data.mongodb.uri=mongodb+srv://sanskrti1910_db_user:S4zUo5PETOJ4h5WB@cluster0.la6zynj.mongodb.net/shopsphere

spring.data.mongodb.auto-index-creation=true

jwt.secret=shopspherejwtsecretkeyforauthentication256bitsecurekey
 
jwt.expiration-ms=86400000
